# Usa una imagen existente como base
FROM nvcr.io/nvidia/rapidsai/base:25.10-cuda13-py3.11

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /workspace

# Copia archivos desde tu directorio del host al contenedor
COPY . /workspace

# Instala las dependencias
RUN python -m pip install -r requirements.txt

# Asegura que JupyterLab esté instalado (la imagen base puede tener solo Jupyter Notebook)
RUN python -m pip install jupyterlab --no-cache-dir