# Usa una imagen existente como base
FROM nvcr.io/nvidia/rapidsai/base:24.06-cuda12.2-py3.9

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /workspace

# Copia archivos desde tu directorio del host al contenedor
COPY . /workspace